FROM node:22-alpine as base
# Install libc6-compat
RUN apk add --no-cache libc6-compat

# Set working directory
WORKDIR /app

# Copy the Prisma files
COPY ./prisma .
RUN  npm i -g pnpm 

# # Run Prisma migrate deploy
CMD ["pnpx", "prisma", "migrate", "deploy"]
