name: Docker Image CI

on:
  pull_request:
    branches: [uat]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version from ./services/auth/package.json
        id: service_auth_version
        run: echo "VERSION_AUTH_SERVICE=$(jq -r .version ./services/auth/package.json)" >> $GITHUB_ENV
      - name: Read version from ./services/auth/package.json
        id: service_mission_version
        run: echo "VERSION_MISSION_SERVICE=$(jq -r .version ./services/mission/package.json)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Medevac Auth Api
        uses: docker/build-push-action@v5
        with:
          context: ./services/auth/
          file: ./Dockerfile
          push: true
          build-args: |
            APP=auth
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/medevac-auth-api:latest
            ${{ secrets.DOCKER_USERNAME }}/medevac-auth-api:${{ env.VERSION_AUTH_SERVICE }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/medevac-auth-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/medevac-auth-api:buildcache,mode=max
      - name: Build and push Medevac Auth Migrate Database
        uses: docker/build-push-action@v5
        with:
          context: ./services/auth/
          file: ./Dockerfile.migration
          push: true
          build-args: |
            APP=auth
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/medevac-auth-migration:latest
            ${{ secrets.DOCKER_USERNAME }}/medevac-auth-migration:${{ env.VERSION_AUTH_SERVICE }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/medevac-auth-migration:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/medevac-auth-migration:buildcache,mode=max
      - name: Build and push Medevac Mission Api
        uses: docker/build-push-action@v5
        with:
          context: ./services/mission/
          file: ./Dockerfile
          push: true
          build-args: |
            APP=mission
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/medevac-mission-api:latest
            ${{ secrets.DOCKER_USERNAME }}/medevac-mission-api:${{ env.VERSION_MISSION_SERVICE }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/medevac-mission-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/medevac-mission-api:buildcache,mode=max
      - name: Build and push Medevac Mission Migrate Database
        uses: docker/build-push-action@v5
        with:
          context: ./services/mission/
          file: ./Dockerfile.migration
          push: true
          build-args: |
            APP=mission
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/medevac-mission-migration:latest
            ${{ secrets.DOCKER_USERNAME }}/medevac-mission-migration:${{ env.VERSION_MISSION_SERVICE }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/medevac-mission-migration:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/medevac-mission-migration:buildcache,mode=max
      # - name: Build and Push Docker Images
      #   run: |
      #           docker-compose -f docker-compose.build.yml build
      #           docker-compose -f docker-compose.build.yml push
