name: Docker Image CI

on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Read version from package.json
              id: package_version
              run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Medevac Auth Api
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      ${{ secrets.DOCKER_USERNAME }}/medevac-auth-api:latest
                      ${{ secrets.DOCKER_USERNAME }}/medevac-auth-api:${{ env.VERSION }}
                  cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/medevac-auth-api:buildcache
                  cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/medevac-auth-api:buildcache,mode=max
