name: Docker Image CI

on:
  pull_request:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version from package.json
        id: package_version
        run: echo "VERSION_AUTH_SERVICE=$(jq -r .version ./services/auth/package.json)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Medevac Auth Api
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./service/auth/Dockerfile
          push: true
          build-args: |
            APP=auth
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/medevac-auth-migration-database:latest
            ${{ secrets.DOCKER_USERNAME }}/medevac-auth-migration-database:${{ env.VERSION }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/medevac-auth-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/medevac-auth-api:buildcache,mode=max
      - name: Build and push Medevac Auth Migrate Database
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./service/auth/Dockerfile
          push: true
          build-args: |
            APP=auth
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/medevac-auth-api:latest
            ${{ secrets.DOCKER_USERNAME }}/medevac-auth-api:${{ env.VERSION }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/medevac-auth-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/medevac-auth-api:buildcache,mode=max
