version: "3.8"
services:
  auth:
    image: "devpala/medevac-auth:latest"
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - APP=auth
  database:
    container_name: medevac-auth-database
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=medevac-auth-password
      - POSTGRES_USER=medevac-auth-user
      - POSTGRES_DB=medevac-auth-database
